services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "8080:80"
      - "8929:22"
    environment:
      GITLAB_ROOT_EMAIL: root@local
      GITLAB_ROOT_PASSWORD: CakeEggMilk11!@
      EXTERNAL_URL: http://gitlab.local
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  harbor-core:
    image: goharbor/harbor-core:v2.11.0
    container_name: harbor-core
    restart: always
    depends_on:
      - harbor-registry
      - harbor-redis
      - harbor-db
    environment:
      CORE_SECRET: harbor12345
      JOBSERVICE_SECRET: jobsecret123
      POSTGRESQL_HOST: harbor-db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: mysecret
      REGISTRY_CONTROLLER_URL: http://harbor-registry:8080
      PORTAL_URL: http://harbor-portal:8080
      LOG_LEVEL: debug
      CACHE_DRIVER: redis
      REDIS_URL: redis://harbor-redis:6379
    volumes:
      - harbor_core_config:/etc/core

  harbor-registry:
    image: goharbor/registry-photon:v2.11.0
    container_name: harbor-registry
    environment:
      REGISTRY_HTTP_ADDR: :8080
    volumes:
      - harbor_registry:/storage

  harbor-redis:
    image: redis:7
    container_name: harbor-redis

  harbor-db:
    image: postgres:13
    container_name: harbor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    volumes:
      - harbor_db:/var/lib/postgresql/data

  harbor-portal:
    image: goharbor/harbor-portal:v2.11.0
    container_name: harbor-portal
    depends_on:
      - harbor-core
    restart: always
    volumes:
      - ./nginx/portal_var_run:/var/run


  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.11.0
    container_name: harbor-jobservice
    restart: always
    depends_on:
      - harbor-core
      - harbor-registry
      - harbor-redis
      - harbor-db
    environment:
      CORE_URL: http://harbor-core:8080
      JOBSERVICE_SECRET: jobsecret123

  harbor-nginx:
    image: goharbor/nginx-photon:v2.11.0
    container_name: harbor-nginx
    restart: always
    depends_on:
      - harbor-portal
      - harbor-jobservice
    ports:
      - "30002:8080"
    volumes:
      - harbor_registry:/storage
      - ./nginx/client_body_temp:/etc/nginx/client_body_temp
      - ./nginx/proxy_temp:/etc/nginx/proxy_temp
      - ./nginx/fastcgi_temp:/etc/nginx/fastcgi_temp
      - ./nginx/uwsgi_temp:/etc/nginx/uwsgi_temp
      - ./nginx/scgi_temp:/etc/nginx/scgi_temp
      - ./nginx/var_run:/var/run

  dind:
    image: docker:dind
    container_name: gitlab-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - /var/lib/docker

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    depends_on:
      - gitlab
      - dind
    restart: always
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_TLS_CERTDIR=""

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
  harbor_db:
  harbor_registry:
  harbor_core_config:

