version: "3.8"

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "8080:80"
      - "8929:22"
    environment:
      GITLAB_ROOT_EMAIL: root@local
      GITLAB_ROOT_PASSWORD: CakeEggMilk11!@
      EXTERNAL_URL: http://gitlab.local
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab

  harbor:
    image: goharbor/harbor-core:v2.11.0
    container_name: harbor-core
    depends_on:
      - registry
      - redis
      - harbor-db
    environment:
      CORE_SECRET: harbor12345
      JOBSERVICE_SECRET: jobsecret123
      POSTGRESQL_HOST: harbor-db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: mysecret
      REGISTRY_CONTROLLER_URL: http://registry:8080
      PORTAL_URL: http://portal:8080
      LOG_LEVEL: debug



  registry:
    image: goharbor/registry-photon:v2.11.0
    container_name: harbor-registry
    environment:
      REGISTRY_HTTP_ADDR: :8080

  redis:
    image: redis:7
    container_name: harbor-redis

  harbor-db:
    image: postgres:13
    container_name: harbor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    volumes:
      - ./data/harbor/db:/var/lib/postgresql/data

  portal:
    image: goharbor/harbor-portal:v2.11.0
    container_name: harbor-portal
    restart: always

  jobservice:
    image: goharbor/harbor-jobservice:v2.11.0
    container_name: harbor-jobservice
    restart: always
    depends_on:
      - harbor-core
    environment:
      CORE_URL: http://harbor-core:8080
      JOBSERVICE_SECRET: jobsecret123

  nginx:
    image: goharbor/nginx-photon:v2.11.0
    container_name: harbor-nginx
    restart: always
    depends_on:
      - portal
      - harbor-core
      - jobservice
    ports:
      - "30002:8080"
    volumes:
      - ./data/harbor/registry:/storage


  dind:
    image: docker:dind
    container_name: gitlab-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - /var/lib/docker

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    depends_on:
      - gitlab
      - dind
    restart: always
    volumes:
      - ./config/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_TLS_CERTDIR=""
